### ISSUE TITLE
[BUG] Shadowy Apparitions animation and speed

### ISSUE THREAD

**Issue by JamminL** [ClassicWoWCommunity/mop-classic-bugs#1641]
#### 1.1. Description
Currently shadowy animations go invisible and sometimes are too slow to the point of almost standing still and never reaching the target
  #### 1.2. How to Reproduce
           1. Shadow Word: Pain some dummies
           2. Run around until they proc
           3. Notice their animation is incorrect and so is the speed at which they walk towards their target
  #### 1.3  Source Material
https://streamable.com/von52k
#### 2.1. Description
Shadowy apparitions animation shouldn't be invisible and their speed should be better dynamicly adjusted
  #### 2.2 Source Material
https://youtu.be/jq7_YcEQhxw?list=PLI89HUBIoWNkUQpYU4yULXLtxNsQTGVq3&t=151

**Comment by Artemishowl** [comment]
Known issue. Impacting Earth, Wind and Fire clones, some other things too. Thanks!

**Comment by AidanZMoon** [comment]
The speed of these should be fixed, the visual will not be done until later

**Comment by Frosttbitten14** [comment]
Spell itself works, speed works. Visual still bugged as of 15/05/25 update

**Comment by Frosttbitten14** [comment]
The animation is still not accurate, don't know why this was closed.

**Comment by AidanZMoon** [comment]
Sent another fix for the speed now.

Should be in some time this week.

**Comment by AidanZMoon** [comment]
Should have been fixed for a while, open a new ticket if the issue is still present.
